"""
Slack reporting tool - sends billing summary + uploads Excel/CSV files
"""

import os
import json
from datetime import datetime
from pathlib import Path
from typing import Any

from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError

SLACK_BOT_TOKEN = os.environ.get("SLACK_BOT_TOKEN", "")
SLACK_CHANNEL   = os.environ.get("SLACK_CHANNEL", "#gcp-billing-alerts")
REPORTS_DIR     = Path(os.environ.get("REPORTS_DIR", "/tmp/billing_reports"))


def _emoji_severity(critical: int, warning: int) -> str:
    if critical > 0:
        return "🔴"
    if warning > 0:
        return "🟡"
    return "🟢"


def send_slack_report(
    org_summary:     dict | None = None,
    anomaly_summary: dict | None = None,
    top_drivers:     dict | None = None,
    excel_filepath:  str  | None = None,
    csv_filepath:    str  | None = None,
) -> dict[str, Any]:
    """
    Send a structured Slack billing report with Excel and CSV file attachments.

    Args:
        org_summary:     Output from fetch_org_billing_summary
        anomaly_summary: Output from detect_billing_anomalies
        top_drivers:     Output from fetch_top_cost_drivers
        excel_filepath:  Path to Excel report file
        csv_filepath:    Path to CSV report file

    Returns:
        dict with 'success', 'message_ts', 'files_uploaded'
    """
    client = WebClient(token=SLACK_BOT_TOKEN)
    run_ts = datetime.now().strftime("%Y-%m-%d %H:%M UTC")

    # ── Determine severity emoji ───────────────────────────────────────────
    critical = anomaly_summary.get("critical_count", 0) if anomaly_summary else 0
    warning  = anomaly_summary.get("warning_count",  0) if anomaly_summary else 0
    sev_emoji = _emoji_severity(critical, warning)

    # ── Header block ──────────────────────────────────────────────────────
    total_cost = f"{org_summary['currency']} {org_summary['total_cost']:,.2f}" if org_summary else "N/A"
    period     = (
        f"{org_summary['period']['start']} → {org_summary['period']['end']}"
        if org_summary else "N/A"
    )
    proj_count = org_summary.get("project_count", 0) if org_summary else 0

    header_text = (
        f"{sev_emoji} *GCP Billing Report* | {run_ts}\n"
        f"*Period:* {period} | *Total Spend:* `{total_cost}` | *Projects:* {proj_count}"
    )

    # ── Anomaly block ─────────────────────────────────────────────────────
    anomaly_lines = []
    if anomaly_summary and anomaly_summary.get("anomalies"):
        for a in anomaly_summary["anomalies"][:5]:  # top 5 in Slack
            sev  = "🔴 CRITICAL" if a["pct_change"] >= 50 else "🟡 WARNING"
            line = (
                f"{sev} `{a['project_id']}` | {a['service']} | "
                f"{a['usage_date']} | +{a['pct_change']}% "
                f"(${a['daily_cost']:,.2f} vs avg ${a['avg_7d_cost']:,.2f})"
            )
            anomaly_lines.append(line)
        if len(anomaly_summary["anomalies"]) > 5:
            anomaly_lines.append(f"_...and {len(anomaly_summary['anomalies'])-5} more (see attached report)_")
    else:
        anomaly_lines.append("✅ No anomalies detected")

    # ── Top drivers block ─────────────────────────────────────────────────
    driver_lines = []
    if top_drivers and top_drivers.get("drivers"):
        for i, d in enumerate(top_drivers["drivers"][:5], 1):
            driver_lines.append(
                f"{i}. `{d['project_name']}` | {d['service']} | "
                f"*${d['total_cost']:,.2f}*"
            )

    # ── Build Slack blocks ────────────────────────────────────────────────
    blocks = [
        {"type": "header", "text": {"type": "plain_text", "text": "📊 GCP Organization Billing Report", "emoji": True}},
        {"type": "section", "text": {"type": "mrkdwn", "text": header_text}},
        {"type": "divider"},
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*🚨 Anomaly Detection*\n" + "\n".join(anomaly_lines)},
        },
    ]

    if driver_lines:
        blocks += [
            {"type": "divider"},
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"*💸 Top 5 Cost Drivers*\n" + "\n".join(driver_lines)},
            },
        ]

    if critical > 0:
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn",
                     "text": f":rotating_light: *Action Required:* {critical} critical anomalies need immediate review."},
        })

    blocks += [
        {"type": "divider"},
        {
            "type": "context",
            "elements": [{"type": "mrkdwn", "text": f"Generated by GCP Billing Agent | {run_ts} | Reports attached below"}],
        },
    ]

    # ── Post message ──────────────────────────────────────────────────────
    try:
        msg_resp = client.chat_postMessage(
            channel=SLACK_CHANNEL,
            blocks=blocks,
            text=f"GCP Billing Report {run_ts} | Spend: {total_cost} | Anomalies: {critical} critical, {warning} warning",
        )
        message_ts = msg_resp["ts"]
    except SlackApiError as e:
        return {"success": False, "error": str(e), "files_uploaded": []}

    # ── Upload files as thread replies ────────────────────────────────────
    files_uploaded = []
    for fpath_str, ftype in [(excel_filepath, "xlsx"), (csv_filepath, "csv")]:
        if not fpath_str:
            continue
        fpath = Path(fpath_str)
        if not fpath.exists():
            # Try resolving relative to REPORTS_DIR
            fpath = REPORTS_DIR / fpath.name
        if not fpath.exists():
            continue
        try:
            up_resp = client.files_upload_v2(
                channel=SLACK_CHANNEL,
                file=str(fpath),
                filename=fpath.name,
                title=f"GCP Billing Report ({ftype.upper()}) - {run_ts}",
                thread_ts=message_ts,
            )
            files_uploaded.append({"filename": fpath.name, "type": ftype, "ok": up_resp["ok"]})
        except SlackApiError as e:
            files_uploaded.append({"filename": str(fpath), "type": ftype, "error": str(e)})

    return {
        "success":        True,
        "message_ts":     message_ts,
        "channel":        SLACK_CHANNEL,
        "files_uploaded": files_uploaded,
        "anomaly_count":  critical + warning,
    }
